version: '3.7'
services:
  mysql:
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=e142125c6b2e2acf7a95264f0328806c4bfac6f023a45b09bf9ed595f4cc6043
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
      